export const MORPHEUS_URLS = [
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/As+long+as+the+Matrix+exists....mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Body+cannot+live.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Desert+of+the+real.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Difference.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Dream.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/He+is+the+one.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Human+race+will+never+be+free.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/No+one+can+be+told....mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/No+one+can+be+told.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Offering+the+truth.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Red+or+blue.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/The+Matrix.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Try+to+relax.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/Welcome+to+the+real+world.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/What+is+the+Matrix.mp3",
    "https://s3.amazonaws.com/matrix-sounds/Morpheus/You+wont+have+to.mp3",
]